- id: '1608842964413'
  alias: Kaarslampjes aan met switch
  description: ''
  trigger:
  - device_id: 35dc19ef4cbbdfcd9c925a7029066f56
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - service: script.kaarslampjes_aan
    data: {}
  mode: single
- id: '1608843088151'
  alias: Kaarslampjes af met switch
  description: ''
  trigger:
  - device_id: 35dc19ef4cbbdfcd9c925a7029066f56
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - service: script.kaarslampjes_af
    data: {}
  mode: single
- id: '1608843338487'
  alias: Kaarslampjes harder met switch
  description: ''
  trigger:
  - device_id: 35dc19ef4cbbdfcd9c925a7029066f56
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_up
  condition: []
  action:
  - service: script.kaarslampjes_harder
    data: {}
  mode: single
- id: '1608843392501'
  alias: Kaarslampjes zachter met switch
  description: ''
  trigger:
  - device_id: 35dc19ef4cbbdfcd9c925a7029066f56
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_down
  condition: []
  action:
  - service: script.kaarslampjes_zachter
    data: {}
  mode: single
- id: '1608845756623'
  alias: Kerstlichtjes aan met switch
  description: ''
  trigger:
  - device_id: 0156f8e1a492a2d497abf8671b8a1032
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - service: script.kerstlichtjes_aan
    data: {}
  mode: single
- id: '1608845782094'
  alias: Kerstlichtjes af met switch
  description: ''
  trigger:
  - device_id: 0156f8e1a492a2d497abf8671b8a1032
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - service: script.kerstlichtjes_af
    data: {}
  mode: single
- id: '1608847512225'
  alias: Computer licht aan met switch
  description: ''
  trigger:
  - device_id: 76d42de4d939ba3ec9c60c7fe69963d4
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - service: script.computer_licht_aan
    data: {}
  mode: single
- id: '1608847544407'
  alias: Computer licht uit met switch
  description: ''
  trigger:
  - device_id: 76d42de4d939ba3ec9c60c7fe69963d4
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - service: script.computer_licht_af
    data: {}
  mode: single
- id: '1608849893807'
  alias: Dressing aan met switch
  description: ''
  trigger:
  - device_id: daa7669e321fc00eafaa21f1c545add7
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - service: script.dressing_aan
    data: {}
  mode: single
- id: '1608849928296'
  alias: Dressing af met switch
  description: ''
  trigger:
  - device_id: daa7669e321fc00eafaa21f1c545add7
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - service: script.dressing_af
    data: {}
  mode: single
- id: '1608849976447'
  alias: Dressing harder met switch
  description: ''
  trigger:
  - device_id: daa7669e321fc00eafaa21f1c545add7
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_up
  condition: []
  action:
  - service: script.dressing_harder
    data: {}
  mode: single
- id: dressingzachtermetswitch
  alias: Dressing zachter met switch
  description: ''
  trigger:
  - device_id: daa7669e321fc00eafaa21f1c545add7
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_down
  condition: []
  action:
  - service: script.dressing_zachter
    data: {}
  mode: single
- id: '1608914545242'
  alias: Salon aan met switch
  description: ''
  trigger:
  - device_id: 33f3807eb386401973cc13e8468cb19a
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - service: script.salon_aan
    data: {}
  mode: single
- id: '1608914561035'
  alias: Salon af met switch
  description: ''
  trigger:
  - device_id: 33f3807eb386401973cc13e8468cb19a
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - service: script.salon_af
    data: {}
  mode: single
- id: '1608920294285'
  alias: Salon harder met switch
  description: ''
  trigger:
  - device_id: 33f3807eb386401973cc13e8468cb19a
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_up
  condition: []
  action:
  - service: script.salon_harder
    data: {}
  mode: single
- id: '1608920327437'
  alias: Salon zachter met switch
  description: ''
  trigger:
  - device_id: 33f3807eb386401973cc13e8468cb19a
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_down
  condition: []
  action:
  - service: script.salon_zachter
    data: {}
  mode: single
