- id: '1608847512225'
  alias: Computer licht aan met switch
  description: ''
  trigger:
  - device_id: 76d42de4d939ba3ec9c60c7fe69963d4
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - service: script.computer_licht_aan
    data: {}
  mode: single
- id: '1608847544407'
  alias: Computer licht uit met switch
  description: ''
  trigger:
  - device_id: 76d42de4d939ba3ec9c60c7fe69963d4
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - service: script.computer_licht_af
    data: {}
  mode: single
- id: '1608849893807'
  alias: Dressing aan met switch
  description: ''
  trigger:
  - device_id: daa7669e321fc00eafaa21f1c545add7
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - service: script.dressing_aan
    data: {}
  mode: single
- id: '1608849928296'
  alias: Dressing af met switch
  description: ''
  trigger:
  - device_id: daa7669e321fc00eafaa21f1c545add7
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - service: script.dressing_af
    data: {}
  mode: single
- id: '1608849976447'
  alias: Dressing harder met switch
  description: ''
  trigger:
  - device_id: daa7669e321fc00eafaa21f1c545add7
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_up
  condition: []
  action:
  - service: script.dressing_harder
    data: {}
  mode: single
- id: dressingzachtermetswitch
  alias: Dressing zachter met switch
  description: ''
  trigger:
  - device_id: daa7669e321fc00eafaa21f1c545add7
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_down
  condition: []
  action:
  - service: script.dressing_zachter
    data: {}
  mode: single
- id: '1619640064633'
  alias: kindersbeneden
  description: Lampjes aan voor de kinderen beneden
  trigger:
  - device_id: 777de08207789a297056a51380c4e79d
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: switch.toggle
    entity_id: switch.stekker_trap
  mode: single
- id: '1642267001589'
  alias: Knopje Marten
  description: ''
  trigger:
  - device_id: 05fd3cb025ead0edd7264c4738a53077
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - type: toggle
    device_id: 94130a1735478084d8fd81f1b10f04bd
    entity_id: light.bureaulampje_marten
    domain: light
  mode: single
- id: '1644923246067'
  alias: Toilet licht uit als er niemand is
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 5b1d4b8de830e5232b3bb2044545a722
    entity_id: binary_sensor.beweging
    domain: binary_sensor
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: sun
    before: sunset
  action:
  - type: turn_off
    device_id: 01b7a129f2b2f754edd93b2d541ac326
    entity_id: light.schakelaar_toilet
    domain: light
  mode: single
- id: '1647694398246'
  alias: Toilet licht aan als iemand binnenkomt
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 5b1d4b8de830e5232b3bb2044545a722
    entity_id: binary_sensor.beweging
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: 01b7a129f2b2f754edd93b2d541ac326
    entity_id: light.schakelaar_toilet
    domain: light
  mode: single
- id: '1648588862573'
  alias: TV af op message
  description: ''
  trigger:
  - platform: mqtt
    topic: HomeAss
    payload: TVOFF
  condition: []
  action:
  - service: androidtv.adb_command
    data:
      command: SLEEP
    target:
      device_id: 54a36ef4ee02425ebaa8dbcd8f59e6fb
  mode: single
- id: '1658314503511'
  alias: HP II increase pages
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.hp_printer_printer
    to:
  condition: []
  action:
  - service: counter.increment
    data: {}
    target:
      entity_id: counter.hp_oj_pages
  mode: single
- id: '1658322629430'
  alias: HP II pages reset
  description: ''
  trigger:
  - platform: time
    at: 00:00:01
  condition:
  - condition: template
    value_template: '{{ now().day == 14 }}'
  action:
  - service: counter.reset
    data: {}
    target:
      entity_id: counter.hp_oj_pages
  mode: single
- id: '1667595438523'
  alias: Warmte Ventilator Toggle
  description: Switch voor warmte ventilator aan/af te zetten
  trigger:
  - device_id: f7cc2232cf146037944830ede1441112
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - type: toggle
    device_id: 8c330a9920c2867ec545b59fa49f07d5
    entity_id: switch.sonoff_2
    domain: switch
  mode: single
- id: '1667597198546'
  alias: Warmte ventilator altijd aan
  description: Wanneer verwarming opspringt moet de ventilator aan
  trigger:
  - platform: state
    entity_id:
    - climate.living_room
    attribute: hvac_action
    to: heating
  condition: []
  action:
  - type: turn_on
    device_id: 8c330a9920c2867ec545b59fa49f07d5
    entity_id: switch.sonoff_2
    domain: switch
  mode: single
- id: '1667858408439'
  alias: Computer power toggle
  description: ''
  trigger:
  - device_id: 6806e2eb4514a4ae38dfe3efb92a9fbd
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - type: toggle
    device_id: e1cf860cf9cc7eeae8e888d696d5b511
    entity_id: switch.lumi_lumi_plug_maeu01_switch
    domain: switch
  mode: single
- id: '1667859651620'
  alias: Kerstlichtjes met groot licht
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: c103650e1bbc5f448a1dd2c476e46b9b
    entity_id: light.schakelaar_salon
    domain: light
  condition: []
  action:
  - type: turn_on
    device_id: 31f93545d5ec6277a0a2c97d4c4de52c
    entity_id: switch.sonoff_1
    domain: switch
  - type: turn_on
    device_id: 485a618ba24d2a8097d856d62eaa3c5f
    entity_id: switch.stekker_kerst_switch
    domain: switch
  mode: single
- id: '1668355492738'
  alias: Stekker Marten aan met switch
  description: ''
  trigger:
  - device_id: 35dc19ef4cbbdfcd9c925a7029066f56
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  - device_id: 35dc19ef4cbbdfcd9c925a7029066f56
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - type: toggle
    device_id: 699039d35483eae11a0e9d58f46d1c6a
    entity_id: switch.stekker_marten_switch
    domain: switch
  mode: single
- id: '1668355988143'
  alias: smorgens stekker marten af na 3 minuten
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 699039d35483eae11a0e9d58f46d1c6a
    entity_id: switch.stekker_marten_switch
    domain: switch
    for:
      hours: 0
      minutes: 3
      seconds: 0
  condition:
  - condition: time
    before: 09:00:00
    after: 06:00:00
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  action:
  - type: turn_off
    device_id: 699039d35483eae11a0e9d58f46d1c6a
    entity_id: switch.stekker_marten_switch
    domain: switch
  mode: single
- id: '1683136009987'
  alias: Publish power produced to mqtt
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.power_produced
  condition:
  - condition: numeric_state
    entity_id: sensor.power_produced
    above: 0.5
  - condition: sun
    before: sunset
    after: sunrise
  action:
  - service: mqtt.publish
    data:
      topic: POWER
      payload_template: '{{ states(''sensor.power_produced'') }} kW'
  mode: single
- id: '1685353333437'
  alias: Publish battery state to mqtt
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.battery_state_of_capacity
  condition:
  - condition: sun
    before: sunset
    after: sunrise
  action:
  - service: mqtt.publish
    data:
      topic: POWER
      payload_template: Batterij {{ states('sensor.battery_state_of_capacity') }}
        %
  mode: single
- id: '1697053616343'
  alias: Set Battery to Time of Use
  description: ''
  trigger:
  - platform: state
    entity_id:
    - schedule.piektarief
    to: 'off'
  condition: []
  action:
  - device_id: 6064c75181b3882bc79c73e4697ecda8
    domain: select
    entity_id: 3dac31fe37c1bc198c46e828c6c539c7
    type: select_option
    option: time_of_use_luna2000
  - type: turn_on
    device_id: 6064c75181b3882bc79c73e4697ecda8
    entity_id: fb5c4056cb8c660009af4c1bef87391c
    domain: switch
  mode: single
- id: '1697057645766'
  alias: Set battery to self-consumption
  description: ''
  trigger:
  - platform: state
    entity_id:
    - schedule.piektarief
    to: 'on'
  condition: []
  action:
  - device_id: 6064c75181b3882bc79c73e4697ecda8
    domain: select
    entity_id: 3dac31fe37c1bc198c46e828c6c539c7
    type: select_option
    option: maximise_self_consumption
  - type: turn_off
    device_id: 6064c75181b3882bc79c73e4697ecda8
    entity_id: fb5c4056cb8c660009af4c1bef87391c
    domain: switch
  mode: single
- id: '1697484774738'
  alias: Badkamer warm on schedule
  description: ''
  trigger:
  - platform: state
    entity_id:
    - schedule.badkamer_warm
    to: 'on'
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: 18
    target:
      entity_id: climate.heat_bad
  mode: single
- id: '1697484905243'
  alias: Badkamer koud on schedule
  description: ''
  trigger:
  - platform: state
    entity_id:
    - schedule.badkamer_warm
    to: 'off'
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: 14
    target:
      entity_id: climate.heat_bad
  mode: single
- id: '1698486723577'
  alias: Badkamer op met switch
  description: ''
  trigger:
  - device_id: 0156f8e1a492a2d497abf8671b8a1032
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  - device_id: 0156f8e1a492a2d497abf8671b8a1032
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - service: script.chauffage_badkamer_even_op
    data: {}
  mode: single
- id: '1701804215115'
  alias: Lampjes Marit toggle
  description: ''
  trigger:
  - device_id: 33f3807eb386401973cc13e8468cb19a
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  - device_id: 33f3807eb386401973cc13e8468cb19a
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - type: toggle
    device_id: f42c2b3d068ed036d43a09b908ecfd1c
    entity_id: 23ef61d420268d59e4f2d54f5b9045f1
    domain: switch
  mode: single
- id: '1701980026087'
  alias: Badkamer heater off when raam open
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 56b5a58590da9e5187780e78fa65ceb2
    entity_id: c7a94997140b9a524a52730144ce20f4
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition: []
  action:
  - device_id: 7d13e1eee46ac7027f84f52ae661c007
    domain: climate
    entity_id: c71d744ef6263d6d0e27c6d0f224a22f
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: single
- id: '1701980073578'
  alias: Badkamer heater on when raam closed
  description: ''
  trigger:
  - type: not_opened
    platform: device
    device_id: 56b5a58590da9e5187780e78fa65ceb2
    entity_id: c7a94997140b9a524a52730144ce20f4
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition: []
  action:
  - device_id: 7d13e1eee46ac7027f84f52ae661c007
    domain: climate
    entity_id: c71d744ef6263d6d0e27c6d0f224a22f
    type: set_hvac_mode
    hvac_mode: heat
  mode: single
- id: '1706571667877'
  alias: Stop laden om 5u30
  description: ''
  trigger:
  - platform: time
    at: 05:30:00
  condition: []
  action:
  - service: script.auto_laden_stop
    data: {}
  mode: single
