- id: '1608847512225'
  alias: Computer licht aan met switch
  description: ''
  trigger:
  - device_id: 76d42de4d939ba3ec9c60c7fe69963d4
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - service: script.computer_licht_aan
    data: {}
  mode: single
- id: '1608847544407'
  alias: Computer licht uit met switch
  description: ''
  trigger:
  - device_id: 76d42de4d939ba3ec9c60c7fe69963d4
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - service: script.computer_licht_af
    data: {}
  mode: single
- id: detectsoffe
  alias: Detecteer boeven
  description: knip toilet aan wanneer beweging aan de auto na zonsondergang
  trigger:
  - type: motion
    platform: device
    device_id: d96497e327bb579b168acbf6fee74b6c
    entity_id: binary_sensor.waakhond_buiten_ias_zone
    domain: binary_sensor
  condition:
  - condition: sun
    after: sunset
  - condition: device
    type: is_off
    device_id: 0fe724dc90023e4571abfb10876f1dd7
    entity_id: light.hue_play_1
    domain: light
  action:
  - service: light.turn_on
    target:
      device_id: 01b7a129f2b2f754edd93b2d541ac326
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    target:
      device_id: 01b7a129f2b2f754edd93b2d541ac326
  mode: single
- id: '1608849893807'
  alias: Dressing aan met switch
  description: ''
  trigger:
  - device_id: daa7669e321fc00eafaa21f1c545add7
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - service: script.dressing_aan
    data: {}
  mode: single
- id: '1608849928296'
  alias: Dressing af met switch
  description: ''
  trigger:
  - device_id: daa7669e321fc00eafaa21f1c545add7
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - service: script.dressing_af
    data: {}
  mode: single
- id: '1608849976447'
  alias: Dressing harder met switch
  description: ''
  trigger:
  - device_id: daa7669e321fc00eafaa21f1c545add7
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_up
  condition: []
  action:
  - service: script.dressing_harder
    data: {}
  mode: single
- id: dressingzachtermetswitch
  alias: Dressing zachter met switch
  description: ''
  trigger:
  - device_id: daa7669e321fc00eafaa21f1c545add7
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_down
  condition: []
  action:
  - service: script.dressing_zachter
    data: {}
  mode: single
- id: '1619640064633'
  alias: kindersbeneden
  description: Lampjes aan voor de kinderen beneden
  trigger:
  - device_id: 777de08207789a297056a51380c4e79d
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: switch.toggle
    entity_id: switch.stekker_trap
  mode: single
- id: '1642267001589'
  alias: Knopje Marten
  description: ''
  trigger:
  - device_id: 05fd3cb025ead0edd7264c4738a53077
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - type: toggle
    device_id: 94130a1735478084d8fd81f1b10f04bd
    entity_id: light.bureaulampje_marten
    domain: light
  mode: single
- id: '1644923246067'
  alias: Toilet licht uit als er niemand is
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 5b1d4b8de830e5232b3bb2044545a722
    entity_id: binary_sensor.beweging
    domain: binary_sensor
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: sun
    before: sunset
  action:
  - type: turn_off
    device_id: 01b7a129f2b2f754edd93b2d541ac326
    entity_id: light.schakelaar_toilet
    domain: light
  mode: single
- id: '1647694398246'
  alias: Toilet licht aan als iemand binnenkomt
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 5b1d4b8de830e5232b3bb2044545a722
    entity_id: binary_sensor.beweging
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: 01b7a129f2b2f754edd93b2d541ac326
    entity_id: light.schakelaar_toilet
    domain: light
  mode: single
- id: '1648588862573'
  alias: TV af op message
  description: ''
  trigger:
  - platform: mqtt
    topic: HomeAss
    payload: TVOFF
  condition: []
  action:
  - service: androidtv.adb_command
    data:
      command: SLEEP
    target:
      device_id: 54a36ef4ee02425ebaa8dbcd8f59e6fb
  mode: single
- id: '1658314503511'
  alias: HP II increase pages
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.hp_printer_printer
    to:
  condition: []
  action:
  - service: counter.increment
    data: {}
    target:
      entity_id: counter.hp_oj_pages
  mode: single
- id: '1658322629430'
  alias: HP II pages reset
  description: ''
  trigger:
  - platform: time
    at: 00:00:01
  condition:
  - condition: template
    value_template: '{{ now().day == 14 }}'
  action:
  - service: counter.reset
    data: {}
    target:
      entity_id: counter.hp_oj_pages
  mode: single
- id: '1667595438523'
  alias: Warmte Ventilator Toggle
  description: Switch voor warmte ventilator aan/af te zetten
  trigger:
  - device_id: f7cc2232cf146037944830ede1441112
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - type: toggle
    device_id: 8c330a9920c2867ec545b59fa49f07d5
    entity_id: switch.sonoff_2
    domain: switch
  mode: single
- id: '1667597198546'
  alias: Warmte ventilator altijd aan
  description: Wanneer verwarming opspringt moet de ventilator aan
  trigger:
  - platform: state
    entity_id:
    - climate.living_room
    attribute: hvac_action
    to: heating
  condition: []
  action:
  - type: turn_on
    device_id: 8c330a9920c2867ec545b59fa49f07d5
    entity_id: switch.sonoff_2
    domain: switch
  mode: single
- id: '1667858408439'
  alias: Computer power toggle
  description: ''
  trigger:
  - device_id: 6806e2eb4514a4ae38dfe3efb92a9fbd
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - type: toggle
    device_id: e1cf860cf9cc7eeae8e888d696d5b511
    entity_id: switch.lumi_lumi_plug_maeu01_switch
    domain: switch
  mode: single
- id: '1667859651620'
  alias: Kerstlichtjes met groot licht
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: c103650e1bbc5f448a1dd2c476e46b9b
    entity_id: light.schakelaar_salon
    domain: light
  condition: []
  action:
  - type: turn_on
    device_id: 31f93545d5ec6277a0a2c97d4c4de52c
    entity_id: switch.sonoff_1
    domain: switch
  - type: turn_on
    device_id: 485a618ba24d2a8097d856d62eaa3c5f
    entity_id: switch.stekker_kerst_switch
    domain: switch
  mode: single
- id: '1668355492738'
  alias: Stekker Marten aan met switch
  description: ''
  trigger:
  - device_id: 35dc19ef4cbbdfcd9c925a7029066f56
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  - device_id: 35dc19ef4cbbdfcd9c925a7029066f56
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - type: toggle
    device_id: 699039d35483eae11a0e9d58f46d1c6a
    entity_id: switch.stekker_marten_switch
    domain: switch
  mode: single
- id: '1668355988143'
  alias: smorgens stekker marten af na 3 minuten
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 699039d35483eae11a0e9d58f46d1c6a
    entity_id: switch.stekker_marten_switch
    domain: switch
    for:
      hours: 0
      minutes: 3
      seconds: 0
  condition:
  - condition: time
    before: 09:00:00
    after: 06:00:00
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  action:
  - type: turn_off
    device_id: 699039d35483eae11a0e9d58f46d1c6a
    entity_id: switch.stekker_marten_switch
    domain: switch
  mode: single
