- id: '1608847512225'
  alias: Computer licht aan met switch
  description: ''
  trigger:
  - device_id: 76d42de4d939ba3ec9c60c7fe69963d4
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - service: script.computer_licht_aan
    data: {}
  mode: single
- id: '1608847544407'
  alias: Computer licht uit met switch
  description: ''
  trigger:
  - device_id: 76d42de4d939ba3ec9c60c7fe69963d4
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - service: script.computer_licht_af
    data: {}
  mode: single
- id: detectsoffe
  alias: Detecteer boeven
  description: knip toilet aan wanneer beweging aan de auto na zonsondergang
  trigger:
  - type: motion
    platform: device
    device_id: d96497e327bb579b168acbf6fee74b6c
    entity_id: binary_sensor.waakhond_buiten_ias_zone
    domain: binary_sensor
  condition:
  - condition: sun
    after: sunset
  - condition: device
    type: is_off
    device_id: 0fe724dc90023e4571abfb10876f1dd7
    entity_id: light.hue_play_1
    domain: light
  action:
  - service: light.turn_on
    target:
      device_id: 01b7a129f2b2f754edd93b2d541ac326
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    target:
      device_id: 01b7a129f2b2f754edd93b2d541ac326
  mode: single
- id: '1608849893807'
  alias: Dressing aan met switch
  description: ''
  trigger:
  - device_id: daa7669e321fc00eafaa21f1c545add7
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - service: script.dressing_aan
    data: {}
  mode: single
- id: '1608849928296'
  alias: Dressing af met switch
  description: ''
  trigger:
  - device_id: daa7669e321fc00eafaa21f1c545add7
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - service: script.dressing_af
    data: {}
  mode: single
- id: '1608849976447'
  alias: Dressing harder met switch
  description: ''
  trigger:
  - device_id: daa7669e321fc00eafaa21f1c545add7
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_up
  condition: []
  action:
  - service: script.dressing_harder
    data: {}
  mode: single
- id: dressingzachtermetswitch
  alias: Dressing zachter met switch
  description: ''
  trigger:
  - device_id: daa7669e321fc00eafaa21f1c545add7
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_down
  condition: []
  action:
  - service: script.dressing_zachter
    data: {}
  mode: single
- id: '1619640064633'
  alias: kindersbeneden
  description: Lampjes aan voor de kinderen beneden
  trigger:
  - device_id: 777de08207789a297056a51380c4e79d
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: switch.toggle
    entity_id: switch.stekker_trap
  mode: single
- id: '1608845756623'
  alias: Kerstlichtjes aan met switch
  description: ''
  trigger:
  - device_id: 0156f8e1a492a2d497abf8671b8a1032
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - service: script.kerstlichtjes_aan
    data: {}
  mode: single
- id: '1608845782094'
  alias: Kerstlichtjes af met switch
  description: ''
  trigger:
  - device_id: 0156f8e1a492a2d497abf8671b8a1032
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - service: script.kerstlichtjes_af
    data: {}
  mode: single
- id: '1608914545242'
  alias: Salon aan met switch
  description: ''
  trigger:
  - device_id: 33f3807eb386401973cc13e8468cb19a
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - service: script.salon_aan
    data: {}
  mode: single
- id: '1608914561035'
  alias: Salon af met switch
  description: ''
  trigger:
  - device_id: 33f3807eb386401973cc13e8468cb19a
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - service: script.salon_af
    data: {}
  mode: single
- id: '1608920294285'
  alias: Salon harder met switch
  description: ''
  trigger:
  - device_id: 33f3807eb386401973cc13e8468cb19a
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_up
  condition: []
  action:
  - service: script.salon_harder
    data: {}
  mode: single
- id: '1608920327437'
  alias: Salon zachter met switch
  description: ''
  trigger:
  - device_id: 33f3807eb386401973cc13e8468cb19a
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_down
  condition: []
  action:
  - service: script.salon_zachter
    data: {}
  mode: single
- id: '1642267001589'
  alias: Knopje Marten
  description: ''
  trigger:
  - device_id: 05fd3cb025ead0edd7264c4738a53077
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - type: toggle
    device_id: 94130a1735478084d8fd81f1b10f04bd
    entity_id: light.bureaulampje_marten
    domain: light
  mode: single
- id: '1644534044224'
  alias: kachel zolder aan
  description: ''
  trigger:
  - device_id: 35dc19ef4cbbdfcd9c925a7029066f56
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - device_id: 2092aa47292b1f8833c908139c0c4e6b
    domain: climate
    entity_id: climate.heater_zolder
    type: set_hvac_mode
    hvac_mode: heat
  mode: single
- id: '1644534062689'
  alias: kachel zolder af
  description: ''
  trigger:
  - device_id: 35dc19ef4cbbdfcd9c925a7029066f56
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - device_id: 2092aa47292b1f8833c908139c0c4e6b
    domain: climate
    entity_id: climate.heater_zolder
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: single
- id: '1644923246067'
  alias: Toilet licht uit als er niemand is
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 5b1d4b8de830e5232b3bb2044545a722
    entity_id: binary_sensor.beweging
    domain: binary_sensor
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: sun
    before: sunset
  action:
  - type: turn_off
    device_id: 01b7a129f2b2f754edd93b2d541ac326
    entity_id: light.schakelaar_toilet
    domain: light
  mode: single
- id: '1647694398246'
  alias: Toilet licht aan als iemand binnenkomt
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 5b1d4b8de830e5232b3bb2044545a722
    entity_id: binary_sensor.beweging
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: 01b7a129f2b2f754edd93b2d541ac326
    entity_id: light.schakelaar_toilet
    domain: light
  mode: single
- id: '1648588862573'
  alias: TV af op message
  description: ''
  trigger:
  - platform: mqtt
    topic: HomeAss
    payload: TVOFF
  condition: []
  action:
  - service: androidtv.adb_command
    data:
      command: SLEEP
    target:
      device_id: 54a36ef4ee02425ebaa8dbcd8f59e6fb
  mode: single
- id: '1658314503511'
  alias: HP II increase pages
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.hp_printer_printer
    above: '0'
  condition: []
  action:
  - service: counter.increment
    data: {}
    target:
      entity_id: counter.hp_oj_pages
  mode: single
- id: '1658322629430'
  alias: HP II pages reset
  description: ''
  trigger:
  - platform: time
    at: 00:00:01
  condition:
  - condition: template
    value_template: '{{ now().day == 14 }}'
  action:
  - service: counter.reset
    data: {}
    target:
      entity_id: counter.hp_oj_pages
  mode: single
