- id: '1608153592961'
  alias: licht en radio aan met knop
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.licht_radio
    from: 'Off'
    to: 'On'
  condition: []
  action:
  - type: turn_on
    device_id: d7792f24ed5ec053ac1e91c6a56967b8
    entity_id: light.kaarslamp_1_level_on_off
    domain: light
    brightness_pct: 35
  - type: turn_on
    device_id: b3774e70723c72440c9040e205a16720
    entity_id: light.kaarslamp_2_level_on_off
    domain: light
    brightness_pct: 35
  - service: media_player.media_play
    data: {}
    entity_id: media_player.libratone_zipp2_709c2c
  mode: single
- id: '1608842964413'
  alias: Kaarslampjes aan
  description: ''
  trigger:
  - device_id: 35dc19ef4cbbdfcd9c925a7029066f56
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - type: turn_on
    device_id: d7792f24ed5ec053ac1e91c6a56967b8
    entity_id: light.kaarslamp_1_level_on_off
    domain: light
    brightness_pct: 35
  - type: turn_on
    device_id: b3774e70723c72440c9040e205a16720
    entity_id: light.kaarslamp_2_level_on_off
    domain: light
    brightness_pct: 35
  mode: single
- id: '1608843088151'
  alias: Kaarslampjes af
  description: ''
  trigger:
  - device_id: 35dc19ef4cbbdfcd9c925a7029066f56
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - type: turn_off
    device_id: d7792f24ed5ec053ac1e91c6a56967b8
    entity_id: light.kaarslamp_1_level_on_off
    domain: light
  - type: turn_off
    device_id: b3774e70723c72440c9040e205a16720
    entity_id: light.kaarslamp_2_level_on_off
    domain: light
  mode: single
- id: '1608843338487'
  alias: Kaarslampjes harder
  description: ''
  trigger:
  - device_id: 35dc19ef4cbbdfcd9c925a7029066f56
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_up
  condition: []
  action:
  - type: brightness_increase
    device_id: d7792f24ed5ec053ac1e91c6a56967b8
    entity_id: light.kaarslamp_1_level_on_off
    domain: light
  - type: brightness_increase
    device_id: b3774e70723c72440c9040e205a16720
    entity_id: light.kaarslamp_2_level_on_off
    domain: light
  mode: single
- id: '1608843392501'
  alias: Kaarslampjes zachter
  description: ''
  trigger:
  - device_id: 35dc19ef4cbbdfcd9c925a7029066f56
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_down
  condition: []
  action:
  - type: brightness_decrease
    device_id: d7792f24ed5ec053ac1e91c6a56967b8
    entity_id: light.kaarslamp_1_level_on_off
    domain: light
  - type: brightness_decrease
    device_id: b3774e70723c72440c9040e205a16720
    entity_id: light.kaarslamp_2_level_on_off
    domain: light
  mode: single
- id: '1608845756623'
  alias: Kerstlichtjes aan
  description: ''
  trigger:
  - device_id: 0156f8e1a492a2d497abf8671b8a1032
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - type: turn_on
    device_id: b21f07e90476116d7f35ca18742aaffd
    entity_id: switch.ikea_of_sweden_tradfri_control_outlet_34277ffe_on_off
    domain: switch
  - type: turn_on
    device_id: 30d516d336cdf0d0a3ae24b010b9d689
    entity_id: switch.tradfri_stekker_2_on_off
    domain: switch
  mode: single
- id: '1608845782094'
  alias: Kerstlichtjes af
  description: ''
  trigger:
  - device_id: 0156f8e1a492a2d497abf8671b8a1032
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - type: turn_off
    device_id: b21f07e90476116d7f35ca18742aaffd
    entity_id: switch.ikea_of_sweden_tradfri_control_outlet_34277ffe_on_off
    domain: switch
  - type: turn_off
    device_id: 30d516d336cdf0d0a3ae24b010b9d689
    entity_id: switch.tradfri_stekker_2_on_off
    domain: switch
  mode: single
- id: '1608847512225'
  alias: Computer licht aan
  description: ''
  trigger:
  - device_id: 76d42de4d939ba3ec9c60c7fe69963d4
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - type: turn_on
    device_id: 0fe724dc90023e4571abfb10876f1dd7
    entity_id: light.hue_play_1
    domain: light
    brightness_pct: 35
  mode: single
- id: '1608847544407'
  alias: Computer licht uit
  description: ''
  trigger:
  - device_id: 76d42de4d939ba3ec9c60c7fe69963d4
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - type: turn_off
    device_id: 0fe724dc90023e4571abfb10876f1dd7
    entity_id: light.hue_play_1
    domain: light
  mode: single
- id: '1608849893807'
  alias: Dressing aan met switch
  description: ''
  trigger:
  - device_id: daa7669e321fc00eafaa21f1c545add7
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - service: script.dressing_aan
    data: {}
  mode: single
- id: '1608849928296'
  alias: Dressing af met switch
  description: ''
  trigger:
  - device_id: daa7669e321fc00eafaa21f1c545add7
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - service: script.dressing_af
    data: {}
  mode: single
- id: '1608849976447'
  alias: Dressing harder met switch
  description: ''
  trigger:
  - device_id: daa7669e321fc00eafaa21f1c545add7
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_up
  condition: []
  action:
  - service: script.dressing_harder
    data: {}
  mode: single
- id: '1608914545242'
  alias: Salon aan met switch
  description: ''
  trigger:
  - device_id: 33f3807eb386401973cc13e8468cb19a
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - service: script.salon_aan
    data: {}
  mode: single
- id: '1608914561035'
  alias: Salon af met switch
  description: ''
  trigger:
  - device_id: 33f3807eb386401973cc13e8468cb19a
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - service: script.salon_af
    data: {}
  mode: single
- id: '1608920294285'
  alias: Salon harder met switch
  description: ''
  trigger:
  - device_id: 33f3807eb386401973cc13e8468cb19a
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_up
  condition: []
  action:
  - service: script.salon_harder
    data: {}
  mode: single
- id: '1608920327437'
  alias: Salon zachter met switch
  description: ''
  trigger:
  - device_id: 33f3807eb386401973cc13e8468cb19a
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_down
  condition: []
  action:
  - service: script.salon_zachter
    data: {}
  mode: single
