
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# https
http:
  server_port: 8123
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 3

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts 
scene: !include scenes.yaml
wirelesstag:
  username: !secret wirelesstags_user
  password: !secret wirelesstags_pass

#Nest config
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  project_id: !secret nest_project_id
  subscriber_id: !secret nest_subscriber_id

spotify:
  client_id: !secret spotify_tim_client
  client_secret: !secret spotify_tim_secret

sensor:
  - platform: wirelesstag
    monitored_conditions:
      - temperature
      - humidity
  - platform: afvalbeheer
    wastecollector: RecycleApp
    resources:
      - restafval
      - gft
      - papier
    postcode: !secret afval_postcode
    streetnumber: !secret afval_number
    streetname: !secret afval_street
  - platform: buienalarm
    timeframe: 15
    name: buienalarm
    monitored_conditions:
      - temperature
      - precipitation
      - precipitation_forecast_average
      - precipitation_forecast_total
      - next_rain_forecast
        #- platform: untappd
        #username: timconinx
        #id:
        #secret: 

ourgroceries:
  username: !secret ourgroceries_username
  password: !secret ourgroceries_password
