
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts 
scene: !include scenes.yaml
wirelesstag:
  username: !secret wirelesstags_user
  password: !secret wirelesstags_pass
sensor:
  - platform: wirelesstag
    monitored_conditions:
      - temperature
      - humidity
#Nest config
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  project_id: !secret nest_project_id
  subscriber_id: !secret nest_subscriber_id

spotify:
  client_id: !secret spotify_tim_client
  client_secret: !secret spotify_tim_secret

