
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# https
http:
  server_port: 8123
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 3

# Text to speech
tts:
  - platform: google_translate

spotcast:
  sp_dc: !secret tim_sp_dc
  sp_key: !secret tim_sp_key

recorder:
  db_url: postgresql://@/homeassistant
  exclude:
    domains:
      - media_player
    entities:
      - sensor.time
      - sensor.date
      - sensor.date_time
      - sensor.date_time_utc
      - sensor.date_time_iso
      - sensor.time_date
      - sensor.time_utc
      - sensor.beat
      - sensor.internet_time

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts 
scene: !include scenes.yaml

shell_command:
  restart_unifi: sudo /home/homeassistant/rootbin/restartunifi.sh
  restart_lms: sudo /home/homeassistant/rootbin/restartlms.sh

#Nest config
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  project_id: !secret nest_project_id
  subscriber_id: !secret nest_subscriber_id

spotify:
  client_id: !secret spotify_tim_client
  client_secret: !secret spotify_tim_secret

# Emby
media_player:
  - platform: emby
    host: !secret emby_host
    api_key: !secret emby_api_key
  - platform: androidtv
    name: ShieldTV
    host: 192.168.1.120

# Xiaomi
fan:
  - platform: xiaomi_miio_airpurifier
    name: Humidifier
    host: 192.168.1.227
    token: !secret xiaomi_token
    model: zhimi.humidifier.ca4
  - platform: xiaomi_miio_airpurifier
    name: Steam Humidifier
    host: 192.168.1.247
    token: !secret xiaomi_token2
    model: deerma.humidifier.jsq
  - platform: xiaomi_miio_fan
    name: Fan
    host: 192.168.1.245
    token: !secret xiaomi_token3
    model: zhimi.fan.za5

binary_sensor:
  - platform: meteoalarm
    country: "belgium"
    province: "Brabant"
    language: "ne"

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'
  - platform: systemmonitor
    resources:
      - type: memory_use_percent
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: processor_use
      - type: processor_temperature
  - platform: afvalbeheer
    wastecollector: RecycleApp
    resources:
      - restafval
      - gft
      - papier
    postcode: !secret afval_postcode
    streetnumber: !secret afval_number
    streetname: !secret afval_street
  - platform: untappd
    username: !secret untappd_username
    id: !secret untappd_id
    secret: !secret untappd_secret

ourgroceries:
  username: !secret ourgroceries_username
  password: !secret ourgroceries_password

template:
  - binary_sensor:
    - name: Battery Tim Low
      unique_id: batterytimlow
      state: "{{ states('sensor.ac2003_battery_level')|int < 25 }}"
  - binary_sensor:
    - name: Battery Kinders Low
      unique_id: batterykinderslow
      state: "{{ states('sensor.tablet_kinders_battery_level')|int < 25 }}"
  - sensor:
    - name: Berekende Windrichting
      unique_id: berekendewindrichting
      state: >
        {% set wind = {
          "bearing" : state_attr('weather.thuisje_hourly', 'wind_bearing')
        } %}

        {% if wind.bearing < 22 %}
          N
        {%- elif wind.bearing < 67 -%}
          NO
        {%- elif wind.bearing < 112 -%}
          O
        {%- elif wind.bearing < 157 -%}
          ZO
        {%- elif wind.bearing < 202 -%}
          Z
        {%- elif wind.bearing < 247 -%}
          ZW
        {%- elif wind.bearing < 292 -%}
          W
        {%- elif wind.bearing < 337 -%}
          NW
        {%- else -%}
          N
        {%- endif %}
  - sensor:
    - name: CO2Waarde
      unique_id: co2waarde
      state: >
        {% if states('sensor.netatmo_indoor_co2')|int < 700 %}
          Perfect
        {%- elif states('sensor.netatmo_indoor_co2')|int < 900 %}
          Goed
        {%- elif states('sensor.netatmo_indoor_co2')|int < 1100 %}
          OK
        {%- elif states('sensor.netatmo_indoor_co2')|int < 1600 %}
          Middelmatig
        {%- else %}
          Slecht
        {%- endif %}


